sudo: required
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
branches:
  only:
    - master
env:
  global:
    - NODE_ENV="test"
    - DEBUG="nsq-strategies:*"
    - NSQ_DOCKERS="cluster"
node_js:
  - "6"
  - "4"
services:
  - docker
install:
  - npm install
  - npm prune
before_script:
  - ./dockers/start.sh
script:
  - make test-coveralls
