sudo: false
language: node_js
env:
- NSQ_DOWNLOAD=nsq-0.3.8.linux-amd64.go1.6.2
node_js:
  - "4.2"
before_script: 
  - wget http://bitly-downloads.s3.amazonaws.com/nsq/$NSQ_DOWNLOAD.tar.gz
  - tar zxvf $NSQ_DOWNLOAD.tar.gz
  - export PATH=$NSQ_DOWNLOAD/bin:$PATH
  - pushd $TRAVIS_BUILD_DIR
  - ./scripts/bootNsq.sh
install:
  - npm install

